server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/yuhang_logs
    redis:
      host: localhost
      port: 6379
      password:      # 如果有密码就写，没有就空着
      database: 0    # 默认使用 0 号库
      timeout: 3000ms
      lettuce: # SpringBoot 2.x 默认使用 Lettuce 连接池
        pool:
          max-active: 8  # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间
          max-idle: 8    # 连接池中的最大空闲连接
          min-idle: 0    # 连接池中的最小空闲连接
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 开发时方便查看SQL（如果不用mybatis-plus的配置）
  jpa:
    properties:
      hibernate:
        format_sql: true
  # 热部署配置（开发环境）
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.yuhang.demo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 密钥：必须是 Base64 编码后的至少 256 位的字符串。
  # 建议使用一个强大的随机生成器生成，这里只是一个示例！
  secret: YXNkaWp5dWhhbmdkZW1vc3ByaW5nYm9vdDNjbG91ZHRpY2tldHNlY3JldGtleQ==
  # 过期时间：例如 1 小时 (60 * 60 * 1000 毫秒)
  expiration: 3600000